4rhd6gh/moviemang

src/components/Icons/StaticIcon.jsx

StaticIcon.jsx hover 효과를 props에서 받는 것이 아니라 컴포넌트 내부  디폴트로 변경

feat(staticicon.jsx): hover opacity 변경을 컴포넌트가 갖는 디폴트 사항으로 변화

---

src/components/Buttons/Button.jsx
src/pages/main/MainPage.jsx

button 컴포넌트 생성했습니다!
prop이 많이 필요해서 작은단위들을(text-color, background-color, border-width, border-radius) 큰 단위로(color, border) 합쳐서 넣었는데 이부분은 추후에 의논해야할거 같습니다!

feat: button component

---

.gitignore
src/components/Icons/DynamicIcon.jsx
src/pages/main/MainPage.jsx
src/stories/DynamicIcon.stories.jsx

DynamicIcon 컴포넌트 생성하였습니다. 구체적으로 전달될 prop이나, 전달하는 두 개의 아이콘을 합쳐서 전달하는 게 나을지에 대한 논의가 추가로 필요할 듯 합니다.

feat: DynamicIcon 컴포넌트 생성

---

src/components/Buttons/Button.jsx
src/pages/main/MainPage.jsx
src/stories/Button.stories.jsx

버튼 컴포넌트 props를 color => textColor, backgroundColor 와 같이 자세히 구분해서 수정해놓았습니다!

button 컴포넌트 수정 및 스토리 북 작성

---

src/components/tag/Tag.jsx
src/stories/StaticIcon.stories.jsx

Primary 이외에 다른 예시들을 스토리북에 보여주는 게 좋을 듯 합니다.

 refactor(스토리북):스토리북 예시 업데이트 

---

src/pages/common/appbar/Appbar.jsx
src/pages/main/MainPage.jsx

- Appbar 컴포넌트 만들어서 메인페이지에 넣어두었습니다.
- 메인페이지 크기를 상대단위를 적용했더니 자꾸 변경돼서 우선 큰화면 기준으로 보기 편하게 해서 작업하기 위해서 고정값으로 변경하였습니다. 차후 반응형 웹 구현하면서 필요에 따라 단위 변경해서 적용하면 될듯합니다.

feat: Appbar 추가 및 페이지 레이아웃 수정

---

src/pages/main/MainPage.jsx

style: 페이지 레이아웃 초안

---

src/pages/main/components/eventBar/index.jsx
src/stories/EventBar.stories.jsx

fix(eventbar/index.jsx): 버튼 컴포넌트의 props 변경에 따른 수정

---

src/pages/common/toggleSwitch/index.jsx
src/stories/ToggleSwitch.stories.jsx

마이페이지랑 회원가입 페이지에서 사용될 컴포넌트라서 common 하위에 생성했습니다. props는 없이 작성했습니다

feat: toggleSwitch 컴포넌트 및 스토리북 생성

---

src/pages/common/movieCard/index.jsx
src/stories/Button.stories.jsx
src/stories/Input.stories.jsx
src/stories/MovieCard.stories.jsx
tailwind.config.js

검색화면에서 쓰일 movieCard 컴포넌트 구현하고 스토리북 추가했습니다.
저번에 파일구조 변경하면서 스토리북에서 생긴 오류 수정했습니다

MovieCard 컴포넌트 구현

---

src/data/movie/actionTypes.js
src/data/movie/actions.js
src/data/movie/reducers.js
src/data/movie/selectors.js
src/data/rootReducer.js
src/data/rootSelectors.js
src/data/user/reducers.js
src/pages/movieList/MovieList.jsx
src/pages/movieList/components/movieCard/index.jsx
src/services/apis/tmMovie/movie/index.js

redux 활용
pages폴더 아래 movieList 폴더를 만들고 안에 components 폴더로 movieCard 컴포넌트 제작
common 폴더에 만들어진 movieCard와 구분할 수 있는 네이밍 필요

movieList 화면 완성

---

src/App.js
src/constants/index.js
src/pages/common/appbar/SearchBar/index.jsx
src/pages/movieList/MovieList.jsx
src/pages/search/Search.jsx
src/pages/search/components/movieSearchCard/index.jsx
src/pages/search/index.jsx
src/services/apis/tmMovie/BaseService.js
src/services/apis/tmMovie/movie/index.js

tmbd 검색 api 구현 했고,
search 페이지에서 필요한 컴포넌트 구현 했습니다.(movieSearchCard)
appbar 안의 search에서 검색 시 navigate로 페이지 이동 구현했습니다.

검색 api 구현, 검색 화면 컴포넌트 구현, 검색 시 navigate 구현

---

src/pages/common/modal/JoinModal.jsx
src/pages/movieList/MovieList.jsx
src/pages/movieList/components/movieCard/index.jsx

- JoinModal 에서 toggleSwitch 컴포넌트 import 시에 오타가 있어 컴파일 되지 않는 문제 수정하였습니다.
- MovieList 페이지 상단 AppBar 조정 및 배경화면 이미지 추가하였습니다.

feat: 오타 수정(JoinModal) / MovieList 페이지 UI 수정

---

src/pages/common/spinner/index.jsx
src/pages/search/Search.jsx

feat: spinner 컴포넌트 생성

---

src/components/Button/index.jsx
src/components/Input/index.jsx
src/pages/common/appbar/Appbar.jsx
src/pages/common/modal/JoinModal.jsx
src/pages/common/modal/LoginModal.jsx

- Button 컴포넌트 width/height 전달하는 형식 변경
- LoginModal/JoinModal CSS 수정
- AppBar JOIN 버튼 CSS 수정
- Button 컴포넌트에 width/height를 더 유동적으로 전달할 수 있도록 아예 전체 텍스트를 전달하는 방식으로 변경하는게 어떨까 해서 변경시켜 보았습니다. 코드 보시고 어떤 방법이 나을지 의견 주시면 감사하겠습니다.
- 로그인/회원가입 모달 CSS 조금씩 수정하였고, input 텍스트 색깔은 우선 검정색으로 해두었습니다. 그리고 placeholder 텍스트 조금씩 변경하였습니다.

Button 컴포넌트 / Modal CSS 수정

---

package-lock.json
src/Layouts/Container.jsx

맡은 페이지 작업하실 때 footer 거슬릴 듯 하여 우선 `hidden` 속성 부여해서 안보이도록 설정해두었습니다.

style(footer component): footer 우선 안보이게 처리

---

src/components/Button/index.jsx
src/pages/common/toggleSwitch/index.jsx
src/pages/mypage/MyPage.jsx
src/pages/mypage/SNB/index.jsx
src/pages/mypage/index.jsx
src/routes/index.jsx

마이페이지 옆 사이드 메뉴 바와 나의 정보페이지 상단부분 구현

feat: myPage 상단 부분 구현

---

src/pages/common/modal/JoinModal.jsx
src/pages/common/timer/index.jsx

- 인증 타이머 컴포넌트 생성
- JoinModal에서 인증버튼 클릭 시 타이머 보이게 구현 / 인증 버튼 -> 확인 버튼으로 변경
- 바깥 영역 클릭해서 모달 닫힐 때, 인증번호 렌더링 여부 결정하는 state false로 변경해주어야 하는데 바깥쪽 클릭하는 로직이 어디에 있는지 못찾았습..니다..
- 인증/확인 버튼 클릭 시에 일어날 일에 대한 로직 더 구체화 필요할듯합니다.

feat(인증타이머): 인증 타이머 구현 및 인증 클릭시 버튼 조건부 렌더링

---

src/pages/movieList/MovieList.jsx
src/pages/search/Search.jsx
src/pages/search/components/movieSearchCard/index.jsx

Search page 인피니티 스크롤 적용
플레이리스트 담기 버튼 디자인 영화상세 페이지와 통일
클릭 했을때 영화 상세 페이지로 가도록 수정

feat(search.jsx): 인피니티 스크롤 적용, +버튼 통일, 클릭이벤트 적용

---

src/components/Button/index.jsx
src/pages/common/appbar/Appbar.jsx
src/pages/common/modal/JoinModal.jsx
src/pages/common/modal/LoginModal.jsx

Button 컴포넌트에 오타로 인해서 버튼 클릭되지 않던 오류 수정하였습니다.

fix: button 컴포넌트에 onclick -> onClick으로 수정
